db_django_uikit_admin:
  image: postgres
app_django_uikit_admin:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db_django_uikit_admin
